- Course Title
- Course Organization 
- Course URL 
- Course Rating 
- Course Difficulty 
- Course Certificate Type 
- Course Duration
- Skills
- Language
- Available Languages 
- Enroll Information
- Assignments Count

In [4]:
import pandas as pd

data = pd.read_csv('data.csv')
metadata = pd.read_csv('course_metadata.csv')

df = data.merge(metadata, on="URL", how="left")
df.head()

Title Organization  \
0                  Google Data Analytics       Google   
1                   Google Cybersecurity       Google   
2             Google Project Management:       Google   
3  Google Digital Marketing & E-commerce       Google   
4                      Google IT Support       Google   

                                                 URL  Rating  \
0  https://www.coursera.org/professional-certific...     4.8   
1  https://www.coursera.org/professional-certific...     4.8   
2  https://www.coursera.org/professional-certific...     4.8   
3  https://www.coursera.org/professional-certific...     4.8   
4  https://www.coursera.org/professional-certific...     4.8   

                                            Metadata  \
0  Beginner · Professional Certificate · 3 - 6 Mo...   
1  Beginner · Professional Certificate · 3 - 6 Mo...   
2  Beginner · Professional Certificate · 3 - 6 Mo...   
3  Beginner · Professional Certificate · 3 - 6 Mo...   
4  Beginner · Professional Certificate · 3 - 6 Mo...   

                                              Skills     Languages Available  \
0  Skills you'll gain: Data Analysis, R Programmi...  11 languages available   
1  Skills you'll gain: Network Security, Python P...  11 languages available   
2  Skills you'll gain: Project Management, Strate...  11 languages available   
3  Skills you'll gain: Digital Marketing, Marketi...  11 languages available   
4  Skills you'll gain: Computer Networking, Netwo...  11 languages available   

           Enroll Information Assignments Count    Taught Language  
0  2,468,706 already enrolled     Not available  Taught in English  
1    759,433 already enrolled     Not available  Taught in English  
2  1,807,675 already enrolled     Not available  Taught in English  
3    831,347 already enrolled     Not available  Taught in English  
4  1,695,991 already enrolled     Not available  Taught in English

In [2]:
print(df.isnull().sum())

Title                    0
Organization             0
URL                      0
Rating                   7
Metadata                 0
Skills                 127
Languages Available      0
Enroll Information      32
Assignments Count        0
Taught Language          0
dtype: int64


In [5]:
len(df)

996

### Metadata

In [3]:
# Normalize Metadata: Extracting Duration, Difficulty, and Type
df[['Difficulty', 'Type', 'Duration']] = df['Metadata'].str.extract(
    r'([\w\s]+)\s·\s([\w\s]+)\s·\s([\w\s\-\d]+)', expand=True
)
df = df.drop(columns=['Metadata'])

### Skills

In [4]:
df['Skills'] = df['Skills'].fillna("").astype(str)

In [5]:
categories = {
    "Data Science": [
        "data", "neural networks", "computer vision", "deep learning", 
        "python", "data analysis", "r programming", "machine learning", 
        "big data", "ai", "statistics", "sql", "data visualization", 
        "power bi", "data engineering", "pandas", "numpy", "databases",
        "scikit-learn", "nlp", "natural language processing",
        "data mining", "pytorch", "tensorflow", "keras"
    ],
    "Engineering and Programming": [
        "engineering", "computer", "databases", "programming", "c++", 
        "web programming", "java", "software development", "hardware", 
        "systems design", "algorithms", "microservices", "cloud",
        "api development", "docker", "kubernetes",  "azure",
        "html", "css", "javascript", "react", "angular", "django", "flask"
        "devops", "cloud computing", "ci/cd", "linux", "bash scripting"
    ],

    "Mathematical Theory and Problem Solving": [
        "mathematics", "linear algebra", "calculus", "theory", "probability", 
        "geometry", "numerical methods", "discrete math", "combinatorics", 
        "differential equations", "optimization", "set theory", 
        "graph theory", "game theory", "mathematical modeling", "logic",
        "problem solving", "critical thinking"
    ],
}

In [6]:
for category in list(categories.keys()):
    column_name = f"{category} Skills Count"
    df[column_name] = 0  # Initialize with 0

In [7]:
for category, keywords in categories.items():
    column_name = f"{category} Skills Count"
    df[column_name] = df['Skills'].apply(
        lambda x: sum(1 for keyword in keywords if keyword.lower() in x.lower())
    )

In [8]:
df['Skills Count'] = df['Skills'].str.split(", ").apply(len)
df['Skills Count']

0      25
1      13
2      24
3      19
4      19
       ..
991     1
992    28
993    25
994    17
995     1
Name: Skills Count, Length: 996, dtype: int64

In [9]:
df = df.drop(columns=['Skills'])

### Taught Language & Languages Available

In [10]:
df['Taught Language'] = df['Taught Language'].str.replace('Taught in ', '', regex=False)
df['Taught Language'].unique()

array(['English', 'Spanish', 'French', 'Japanese', 'Portuguese (Brazil)'],
      dtype=object)

In [11]:
df['Languages Available'] = df['Languages Available'].str.extract('(\d+)')
df['Languages Available'].unique()

array(['11', '21', '22', '24', '25', nan, '23', '20', '13', '7', '3', '4',
       '9'], dtype=object)

In [12]:
df['Languages Available'] = df['Languages Available'].fillna(0).astype(int)

### Enroll Information

In [13]:
df['Enroll Information'] = df['Enroll Information'].str.replace(' already enrolled', '', regex=False)
df['Enroll Information'].unique()

array(['2,468,706', '759,433', '1,807,675', '831,347', '1,695,991',
       '1,105,689', '533,425', '889,704', '897,465', '657,138', '322,536',
       '2,331', '137,573', '42,540', '187,931', nan, '145,507', '13,088',
       '220,840', '82,273', '2,149,345', '1,531,067', '2,929,734',
       '55,846', '21,150', '101,323', '268,190', '993,872', '92,413',
       '9,664', '330,579', '67,388', '798,487', '742,554', '49,272',
       '15,151', '35,854', '15,887', '434,240', '20,760', '6,629',
       '73,734', '14,554', '1,122,158', '46,082', '11,733', '1,714,797',
       '14,517', '321,518', '33,628', '20,077', '1,897,037', '5,187',
       '188,623', '1,585', '26,348', '22,031', '37,258', '3,421',
       '11,966', '93,154', '20,395', '92,794', '410,719', '2,071,773',
       '791,550', '26,204', '1,157,517', '59,781', '10,859', '424,015',
       '28,540', '6,659', '60,370', '1,364,559', '109,465', '6,489',
       '23,933', '5,091', '5,592', '612,144', '3,240', '5,894', '45,764',
       '4,146',

In [14]:
df['Enroll Information'] = df['Enroll Information'].str.replace(',', '')
df['Enroll Information'] = df['Enroll Information'].fillna(0).astype(int)

In [15]:
df['Enroll Information']

0      2468706
1       759433
2      1807675
3       831347
4      1695991
        ...   
991     161059
992     128593
993       6634
994      30607
995      19966
Name: Enroll Information, Length: 996, dtype: int32

### Assignments Count

In [16]:
df['Assignments Count'].unique()

array(['Not available', '12 assignments', '4 quizzes, 11 assignments',
       '4 assignments', '8 quizzes, 9 assignments',
       '5 quizzes, 8 assignments', '9 assignments',
       '7 quizzes, 9 assignments', '3 assignments',
       '15 quizzes, 4 assignments', '15 quizzes', '25 assignments',
       '7 quizzes, 10 assignments', '22 quizzes, 2 assignments',
       '6 assignments', '11 quizzes, 6 assignments', '19 quizzes',
       '14 assignments', '32 quizzes', '24 quizzes, 5 assignments',
       '20 quizzes, 11 assignments', '11 quizzes, 9 assignments',
       '18 quizzes, 3 assignments', '21 quizzes, 3 assignments',
       '11 quizzes, 4 assignments', '16 quizzes, 5 assignments',
       '13 assignments', '20 assignments', '10 quizzes, 17 assignments',
       '30 quizzes', '23 assignments', '8 assignments',
       '18 quizzes, 20 assignments', '26 quizzes',
       '17 quizzes, 1 assignment', '37 quizzes, 1 assignment',
       '11 assignments', '5 assignments', '12 quizzes, 12 assignme

In [17]:
df['Quizzes'] = df['Assignments Count'].str.extract(r'(\d+)\s*quizzes').fillna(0).astype(int)
df['Assignments'] = df['Assignments Count'].str.extract(r'(\d+)\s*assignments').fillna(0).astype(int)
df = df.drop(columns=['Assignments Count'])

In [18]:
df['Quizzes'].unique()

array([ 0,  4,  8,  5,  7, 15, 22, 11, 19, 32, 24, 20, 18, 21, 16, 10, 30,
       26, 17, 37, 12, 23, 29, 13,  9, 34,  2,  3, 27, 31, 14])

In [19]:
df['Assignments'].unique()

array([  0,  12,  11,   4,   9,   8,   3,  25,  10,   2,   6,  14,   5,
        13,  20,  17,  23,  18,   7,  24,  22,  52,  21,  33,  15,  35,
        26,  39,  30,  56,  70,  29,  16,  40,  19,  62,  28,  36,  27,
        45,  44,  43, 136,  59])

### Rating

In [20]:
data['Rating'].unique()

array([4.8, 4.9, 4.7, 4.6, 4.5, 4.1, 4.4, nan, 4. , 3.9, 4.2, 4.3, 5. ,
       2.4, 2.8])

In [21]:
data['Rating'].value_counts(dropna=False)

Rating
4.8    314
4.7    295
4.6    189
4.9     66
4.5     64
4.4     29
4.3     12
4.2      8
NaN      7
3.9      5
4.1      3
4.0      1
5.0      1
2.4      1
2.8      1
Name: count, dtype: int64

In [22]:
data = data.dropna(subset=['Rating'])

In [23]:
data['Rating'].dtype

dtype('float64')

Column Data Types

Count Null Cells for Each Row

Count Null Cells for Each Column

In [24]:
print(df.dtypes)

Title                                                    object
Organization                                             object
URL                                                      object
Rating                                                  float64
Languages Available                                       int32
Enroll Information                                        int32
Taught Language                                          object
Difficulty                                               object
Type                                                     object
Duration                                                 object
Data Science Skills Count                                 int64
Engineering and Programming Skills Count                  int64
Mathematical Theory and Problem Solving Skills Count      int64
Skills Count                                              int64
Quizzes                                                   int32
Assignments                             

In [25]:
null_rows = df[df.isnull().any(axis=1)]
print(null_rows)

                                              Title  \
167                         AI Python for Beginners   
275            Introduction to Financial Accounting   
347                                 Microsoft Excel   
635  Introduction to Public Relations and the Media   
707                Introduction to Forensic Science   
923                            Fractal Data Science   
959       Personal Branding: Stand Out and Succeed    

                                    Organization  \
167                              DeepLearning.AI   
275                   University of Pennsylvania   
347                                    Microsoft   
635               University of Colorado Boulder   
707  Nanyang Technological University, Singapore   
923                            Fractal Analytics   
959                       University of Michigan   

                                                   URL  Rating  \
167  https://www.coursera.org/learn/ai-python-for-b...     NaN   
275  https

In [26]:
df = df.dropna()

In [28]:
column_null_counts = df.isnull().sum()
print(column_null_counts)

Title                                                   0
Organization                                            0
URL                                                     0
Rating                                                  0
Languages Available                                     0
Enroll Information                                      0
Taught Language                                         0
Difficulty                                              0
Type                                                    0
Duration                                                0
Data Science Skills Count                               0
Engineering and Programming Skills Count                0
Mathematical Theory and Problem Solving Skills Count    0
Skills Count                                            0
Quizzes                                                 0
Assignments                                             0
dtype: int64


In [29]:
df.to_csv('cleaned_data.csv', index=False, encoding='utf-8')